export const ActionTypes = {
  ESTABLISHED_CONNECTION: 'ESTABLISHED_CONNECTION',
  GET_INITIAL_USERS: 'GET_INITIAL_USERS',
  ADD_USER: 'ADD_USER',
  REMOVE_USER: 'REMOVE_USER',
  ADD_PUBLIC_MESSAGE: 'ADD_PUBLIC_MESSAGE',
  SEND_PRIVATE_MESSAGE: 'SEND_PRIVATE_MESSAGE',
  RECEIVE_PRIVATE_MESSAGE: 'RECEIVE_PRIVATE_MESSAGE',
};